workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - github
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
      cancel_previous_builds: true
    artifacts:
      - app/build/outputs/bundle/**/*.aab
    scripts:
      #- name: App test
       # script: ./gradlew testReleaseUnitTest
      - name: App lint
        script: ./gradlew lintReportRelease
      - name: Sonar Analyze
        script: ./gradlew sonar
      - name: Build Android app
        script: ./gradlew assembleRelease
        #script: |
        #bash gradlew ":app:assembleRelease"
