workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - github
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
      cancel_previous_builds: true
    artifacts:
      - app/build/outputs/bundle/**/*.aab
    scripts:
      #- name: App test
      #  script: ./gradlew testDebugUnitTest
      - name: Run unit tests
        script: ./gradlew testDebugUnitTest
        test_report: app/build/**/*.xml
      - name : App test report
        script: ./gradlew jacocoTestReport
      - name: App lint
        script: ./gradlew lintReportDebug
      - name: Sonar Analyze
        script: ./gradlew sonar
      - name: Build Android app
        script: ./gradlew assembleRelease
        #script: |
        #bash gradlew ":app:assembleRelease"
