workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - github
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    artifacts:
      - app/build/outputs/bundle/**/*.aab
    scripts:
      #- name: Sonar Analyze
       # script: ./gradlew sonarqube
      - name: Build Android app
        script: ./gradlew assembleRelease
        #script: |
        #bash gradlew ":app:assembleRelease"
